In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import cv2

In [2]:
DATADIR = "C:\\Users\\Shibu2\\Downloads\\Dataset\\PetImages"
CATEGORY = ["Dog","Cat"]
IMG_SIZE = 50
training_data = []

#new_array = cv2.resize(img_array, (IMG_SIZE,IMG_SIZE))
def create_training_data():    
    for categories in CATEGORY:
        path = os.path.join(DATADIR,categories)   #to access C:\\Users\\Shibu2\\Downloads\\Dataset\\PetImages\\Dog or Cat
        class_num = CATEGORY.index(categories)
        for img in os.listdir(path): # to access each image in the directory
            try:
                img_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE) #convt to greyscale cuz it's not a differentiating factor
                new_array = cv2.resize(img_array, (IMG_SIZE,IMG_SIZE))
                training_data.append([new_array, class_num]) #1st row will be img array 2nd will be the labels
            except Exception as e:
                pass

create_training_data()

In [3]:
print(len(training_data))

24946


In [4]:
import random
random.shuffle(training_data)

In [5]:
for sample in training_data[:10]:
    print(sample[0])

[[ 45  48  49 ...  56  50  54]
 [ 55  51  55 ...  56  52  55]
 [ 51  55  53 ...  52  54  59]
 ...
 [129 141 134 ... 153 152 151]
 [135 136 134 ... 156 151 153]
 [123 140 130 ... 154 156 155]]
[[204  94 197 ... 160 155 159]
 [204 101 190 ... 161 152 159]
 [203  97 187 ... 147 148 156]
 ...
 [146 152 151 ... 143 144 142]
 [151 153 151 ... 145 140 143]
 [153 159 154 ... 155 150 148]]
[[ 26  26  28 ... 165 161 155]
 [ 28  28  20 ... 169 164 163]
 [ 32  36  34 ... 172 168 163]
 ...
 [ 12  12  11 ... 135 171 121]
 [ 10  11  13 ... 131 165 120]
 [ 11  11  12 ... 128 154 122]]
[[ 72  76  82 ...  99  95  96]
 [ 72  82  88 ...  98  97  96]
 [ 69  81  86 ... 104  99  99]
 ...
 [123 125 129 ... 142 138 136]
 [122 125 123 ... 134 137 132]
 [117 111 120 ... 132 136 134]]
[[46 48 49 ... 66 67 67]
 [50 51 51 ... 67 67 70]
 [52 52 52 ... 68 68 70]
 ...
 [68 69 82 ... 77 84 81]
 [76 84 91 ... 73 90 84]
 [79 75 89 ... 77 77 66]]
[[ 24  58  61 ...  50  60  23]
 [ 23  59  64 ...  50  63  24]
 [ 26  57  65 

In [6]:
X = []
y = []

In [7]:
for features, labels in training_data:
    X.append(features)
    y.append(labels)

X = np.array(X).reshape(-1,IMG_SIZE,IMG_SIZE,1) 
y = np.array(y)

In [8]:
import pickle

pickle_out = open("X.pickle", "wb")
pickle.dump(X, pickle_out)
pickle_out.close()

pickle_out = open("y.pickle", "wb")
pickle.dump(y, pickle_out)
pickle_out.close()